const imagePath = '../'

export const underLine = `${imagePath}/underline.png`
export const radial = `${imagePath}/radial.png`
export const title = `${imagePath}/Title.png`
export const titleSmall = `${imagePath}/TitleSmall.png`
export const manWearGlass = `${imagePath}/man-wearing-smart (1).svg`
export const starBall = `${imagePath}/ballstar.svg`
export const bigIdea = `${imagePath}/Thebigidea.png`
export const rulesregulation = `${imagePath}/ruleandregulation.png`
export const criteria = `${imagePath}/criteria.png`
export const trophy = `${imagePath}/trophy.png`
export const reward = `${imagePath}/Rewards.png`
export const liberty1 = `${imagePath}/liberty1.png`
export const liberty2 = `${imagePath}/liberty2.png`
export const Paybox = `${imagePath}/Paybox.png`
export const Visual6 = `${imagePath}/Vizual6.png`
export const winwise3 = `${imagePath}/winwise3.png`
export const wisper4 = `${imagePath}/wisper4.png`
export const manonpadlock = `${imagePath}/manonpadlock.png`
export const Vector = `${imagePath}/Vector.png`
export const casualworker = `${imagePath}/casualworker.png`
export const formBg = `${imagePath}/Rectangle 10.png`
export const graphicDesigner = `${imagePath}/graphic-designer.png`
export const moving1 = `${imagePath}/moving1.png`
export const moving2 = `${imagePath}/moving2.png`
export const success = `${imagePath}/congratulation.png`